### PR TITLE
variables/constants/methods should be marked as private unless they need exposure

### PR DESCRIPTION
**Pull request by sallyransom**
@iovortex @tLewisII @Cananito @yfujiki please review

### CODE REVIEW

**Comment by Cananito** [comment]
@sallyransom Totes agree :+1: . Not sure is this is a grouping suggestion or adequate for this PR: but how about grouping everything by their access level? Without headers, a list of mixed methods makes it very hard to find stuff.

**Comment by sallyransom** [comment]
@Cananito Do u mean grouping items that are private/public/internal across the board? If so, methinks not.

**Comment by Cananito** [comment]
@sallyransom Kinda. Not across the board, but in the sub-groups or inside a class/struct/enum:

``` swift
class A {
    // MARK: Constants
    public let x = 1.0
    private let y = 5.0

    // Mark: ?
    public b() {}
    public c() {}
    d() {}
    private e() {}
}
```

**Comment by sallyransom** [comment]
@Cananito oh. i think i get what you mean. is it this #7 ?

**Comment by sallyransom** [comment]
@Cananito i made another pr to the effect with #8

**Pull request merged**
